import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { expect, test, vi } from 'vitest'

import { ActionsPage } from './ActionsPage'
import * as api from './api'
import * as runsApi from '../predictions/api'
import type { ActionPlanList } from '../../shared/api/types'
import type { PredictionRunList, PredictionResults } from '../../shared/api/types'

const mocks = vi.hoisted(() => ({
  hasRole: vi.fn(),
}))

vi.mock('../../app/AuthContext', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../../app/AuthContext')>()
  return {
    ...actual,
    useAuth: () => ({
      login: vi.fn(),
      logout: vi.fn(),
      user: null,
      status: 'authenticated' as const,
      hasRole: mocks.hasRole,
    }),
  }
})

vi.mock('./api')
vi.mock('../predictions/api')

const PLANS: ActionPlanList = {
  items: [
    {
      id: 'plan-1',
      prediction_result_id: 'r-1',
      run_id: 'run-1',
      city_code: '222401',
      city_name: '延吉',
      status: 'pending_review',
      generator_type: 'rule_fallback',
      generation_note: 'generated by deterministic rule template',
      target_segment: '年轻情侣与摄影客群',
      action_window_start: '2026-08-19',
      action_window_end: '2026-09-02',
      product_bundle: [{ type: '交通', reason: '可达性 66', priority: 'P1' }],
      campaign_theme: '抢先体验',
      supply_actions: ['直达交通优先上线'],
      assumptions: ['扩散持续'],
      risk_notes: '立即人工研判与备供',
      created_by: 'u1',
      created_at: '2026-08-16T11:00:00+08:00',
      updated_at: '2026-08-16T11:00:00+08:00',
      reviewed_by: null,
      reviewed_at: null,
      review_comment: null,
    },
  ],
  total: 1,
}

const EMPTY_RUNS: PredictionRunList = { items: [], total: 0 }
const NO_RESULTS: PredictionResults = {
  run: {
    id: 'run-1',
    window_days: 14,
    status: 'succeeded',
    as_of_date: '2026-08-16',
    city_count: 0,
    scoring_version_id: 'sv',
    data_fingerprint: 'x',
    created_at: '2026-08-16',
    finished_at: null,
    error: null,
  },
  items: [],
}

function renderPage() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  return render(
    <QueryClientProvider client={client}>
      <ActionsPage />
    </QueryClientProvider>,
  )
}

test('lists plans with status and generator badges', async () => {
  mocks.hasRole.mockReturnValue(false)
  vi.mocked(api.listPlans).mockResolvedValue(PLANS)
  vi.mocked(runsApi.listRuns).mockResolvedValue(EMPTY_RUNS)

  renderPage()

  expect(await screen.findByText('年轻情侣与摄影客群')).toBeInTheDocument()
  expect(screen.getAllByText('待审批').length).toBeGreaterThanOrEqual(2)
  expect(screen.getAllByText('规则模板').length).toBeGreaterThanOrEqual(2)
})

test('operator can approve a pending plan', async () => {
  mocks.hasRole.mockImplementation((role: string) => role === 'operator')
  const approved = { ...PLANS.items[0], status: 'approved' as const }
  vi.mocked(api.listPlans).mockResolvedValue(PLANS)
  vi.mocked(api.reviewPlan).mockResolvedValue(approved)
  vi.mocked(runsApi.listRuns).mockResolvedValue(EMPTY_RUNS)

  renderPage()

  const comment = await screen.findByLabelText('审批意见')
  fireEvent.change(comment, { target: { value: '证据充分' } })
  fireEvent.click(screen.getByRole('button', { name: '批准' }))

  await waitFor(() => expect(api.reviewPlan).toHaveBeenCalledWith('plan-1', 'approved', '证据充分'))
})

test('analyst sees generate dropdown but no approve buttons', async () => {
  mocks.hasRole.mockImplementation((role: string) => role === 'analyst')
  vi.mocked(api.listPlans).mockResolvedValue({ items: [], total: 0 })
  vi.mocked(runsApi.listRuns).mockResolvedValue({
    items: [
      {
        id: 'run-1',
        window_days: 14,
        status: 'succeeded',
        as_of_date: '2026-08-16',
        city_count: 1,
        scoring_version_id: 'sv',
        data_fingerprint: 'x',
        created_at: '2026-08-16',
        finished_at: null,
        error: null,
      },
    ],
    total: 1,
  })
  vi.mocked(runsApi.runResults).mockResolvedValue(NO_RESULTS)

  renderPage()

  expect(await screen.findByLabelText('选择城市结果')).toBeInTheDocument()
  expect(screen.queryByRole('button', { name: '批准' })).not.toBeInTheDocument()
})
