import json
import urllib.request
import uuid
from datetime import UTC, datetime

import sqlalchemy as sa
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from citypulse.actions.deepseek import deepseek_draft, merge_generated
from citypulse.actions.feishu import notify as notify_feishu
from citypulse.actions.generator import rule_draft
from citypulse.actions.models import ActionPlan, ActionPlanVersion
from citypulse.identity.rbac import Identity
from citypulse.prediction.service import get_result
from citypulse.shared.config import get_settings
from citypulse.shared.errors import AppError

REVIEW_TRANSITIONS = {
    "draft": {"draft", "pending_review", "archived"},
    "pending_review": {"approved", "rejected", "draft"},
    "approved": {"archived"},
    "rejected": {"archived", "draft"},
}


def _http_post_json(
    url: str, *, headers: dict[str, str], body: dict[str, object]
) -> dict[str, object]:
    request = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers=headers,
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=12) as response:
        return json.loads(response.read().decode("utf-8"))


PLAN_SNAPSHOT_FIELDS = (
    "status",
    "target_segment",
    "campaign_theme",
    "risk_notes",
    "action_window_start",
    "action_window_end",
    "supply_actions",
    "review_comment",
)


async def record_plan_version(
    db: AsyncSession,
    plan: ActionPlan,
    *,
    event: str,
    actor_id: uuid.UUID | None = None,
    note: str | None = None,
) -> ActionPlanVersion:
    result = await db.execute(
        select(sa.func.coalesce(sa.func.max(ActionPlanVersion.version_no), 0)).where(
            ActionPlanVersion.plan_id == plan.id
        )
    )
    next_no = int(result.scalar_one()) + 1
    snapshot = {field: getattr(plan, field) for field in PLAN_SNAPSHOT_FIELDS}
    for key, value in snapshot.items():
        if hasattr(value, "isoformat"):
            snapshot[key] = value.isoformat()
    version = ActionPlanVersion(
        plan_id=plan.id,
        version_no=next_no,
        event=event,
        snapshot=snapshot,
        actor_id=actor_id,
        note=note,
    )
    db.add(version)
    await db.flush()
    return version


async def list_plan_versions(
    db: AsyncSession, plan_id: uuid.UUID
) -> list[ActionPlanVersion]:
    result = await db.execute(
        select(ActionPlanVersion)
        .where(ActionPlanVersion.plan_id == plan_id)
        .order_by(ActionPlanVersion.version_no)
    )
    return list(result.scalars())


async def get_plan(db: AsyncSession, plan_id: uuid.UUID) -> ActionPlan:
    result = await db.execute(select(ActionPlan).where(ActionPlan.id == plan_id))
    plan = result.scalar_one_or_none()
    if plan is None:
        raise AppError(
            code="PLAN_NOT_FOUND", message="The action plan does not exist.", status_code=404
        )
    return plan


async def generate_plan(
    db: AsyncSession, *, prediction_result_id: uuid.UUID, identity: Identity
) -> ActionPlan:
    result = await get_result(db, prediction_result_id)
    as_of = datetime.now(UTC).date()
    draft = rule_draft(result, as_of=as_of)

    settings = get_settings()
    generator_type = "rule_fallback"
    note = "generated by deterministic rule template"
    api_key = settings.deepseek_api_key.get_secret_value()
    if api_key:
        payload = deepseek_draft(
            result,
            api_key=api_key,
            base_url=settings.deepseek_base_url,
            post_json=_http_post_json,
        )
        if payload is not None:
            draft = merge_generated(draft, payload)
            generator_type = "deepseek"
            note = "generated by DeepSeek with schema validation"
        else:
            note = "DeepSeek call failed or invalid; rule template used"

    plan = ActionPlan(
        prediction_result_id=result.id,
        run_id=result.run_id,
        city_code=result.city_code,
        city_name=result.city_name,
        generator_type=generator_type,
        generation_note=note,
        target_segment=draft.target_segment,
        action_window_start=draft.action_window_start,
        action_window_end=draft.action_window_end,
        product_bundle=draft.product_bundle,
        campaign_theme=draft.campaign_theme,
        supply_actions=draft.supply_actions,
        assumptions=draft.assumptions,
        risk_notes=draft.risk_notes,
        created_by=identity.user_id,
    )
    db.add(plan)
    await db.flush()
    await record_plan_version(
        db, plan, event="generated", actor_id=identity.user_id, note=plan.generator_type
    )
    return plan


async def update_plan(
    db: AsyncSession,
    plan: ActionPlan,
    *,
    target_segment: str | None = None,
    campaign_theme: str | None = None,
    risk_notes: str | None = None,
    action_window_start=None,
    action_window_end=None,
    supply_actions: list[str] | None = None,
) -> ActionPlan:
    if plan.status not in ("draft",):
        raise AppError(
            code="PLAN_IMMUTABLE_AFTER_SUBMIT",
            message="Only drafts can be edited; archive and regenerate instead.",
            status_code=409,
        )
    if target_segment is not None:
        plan.target_segment = target_segment
    if campaign_theme is not None:
        plan.campaign_theme = campaign_theme
    if risk_notes is not None:
        plan.risk_notes = risk_notes
    if action_window_start is not None:
        plan.action_window_start = action_window_start
    if action_window_end is not None:
        plan.action_window_end = action_window_end
    if supply_actions is not None:
        plan.supply_actions = supply_actions
    await db.flush()
    await record_plan_version(db, plan, event="edited", actor_id=plan.created_by)
    return plan


def transition(plan: ActionPlan, target: str) -> None:
    allowed = REVIEW_TRANSITIONS.get(plan.status, set())
    if target not in allowed:
        raise AppError(
            code="INVALID_PLAN_TRANSITION",
            message=f"Cannot move a {plan.status} plan to {target}.",
            status_code=409,
        )
    plan.status = target


async def submit_plan(db: AsyncSession, plan: ActionPlan, *, identity: Identity) -> ActionPlan:
    transition(plan, "pending_review")
    await db.flush()
    await record_plan_version(
        db, plan, event="submitted", actor_id=identity.user_id
    )
    return plan


async def review_plan(
    db: AsyncSession,
    plan: ActionPlan,
    *,
    decision: str,
    comment: str | None,
    identity: Identity,
) -> ActionPlan:
    if decision not in ("approved", "rejected"):
        raise AppError(
            code="INVALID_DECISION",
            message="Decision must be approved or rejected.",
            status_code=400,
        )
    transition(plan, decision)
    plan.reviewed_by = identity.user_id
    plan.reviewed_at = datetime.now(UTC)
    plan.review_comment = comment
    await db.flush()
    await record_plan_version(
        db, plan, event=decision, actor_id=identity.user_id, note=comment
    )
    if decision == "approved":
        from citypulse.shared.config import get_settings

        notify_feishu(get_settings().feishu_webhook, plan)
    return plan


async def list_plans(
    db: AsyncSession, *, status: str | None = None, limit: int = 50
) -> list[ActionPlan]:
    statement = select(ActionPlan).order_by(sa.desc(ActionPlan.created_at)).limit(limit)
    if status:
        statement = statement.where(ActionPlan.status == status)
    return list((await db.execute(statement)).scalars())
